AplicacionUsuarioAC/src/AplicacionUsuarioAC/Models/Usuario.cs
using System;

namespace AplicacionUsuarioAC.Models
{
    public class Usuario
    {
        public string Nombre { get; set; }
        public string Email { get; set; }
        public string Pais { get; set; }
        public bool Estado { get; set; }
        public DateTime FechaUltimoLogin { get; set; }
         
    }
}

AplicacionUsuarioAC/src/AplicacionUsuarioAC/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.InteropServices.ComTypes;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace AplicacionUsuarioAC.Controllers
{
    public class HomeController : Controller
    {
        
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Error()
        {
            return View();
        }
    }
}

AplicacionUsuarioAC/src/AplicacionUsuarioAC/Controllers/ListarController.cs
using AplicacionUsuarioAC.Reposity.Listar;
using Microsoft.AspNetCore.Mvc;
using AplicacionUsuarioAC.Models;
using System;

namespace AplicacionUsuarioAC.Controllers
{
    public class ListarController : Controller
    {
        UsuariosRepository _usuariosRepository;
        
        public IActionResult Usuarios()
        {
            _usuariosRepository = new UsuariosRepository();
            var model = _usuariosRepository.DameLosUsuarios();
            return View(model);
        }

        public IActionResult AltaUsuario()
        {
            return View();
        }

        public IActionResult AgregarUsuario(string nombre, string email, string pais, bool estado)
        {
            var model = new Usuario()
            {
                Nombre = nombre,
                Email = email,
                Pais = pais,
                FechaUltimoLogin = DateTime.Now,
                Estado = estado
            };
            return PartialView("_usuario", model);
        }
    }
}

AplicacionUsuarioAC/src/AplicacionUsuarioAC/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"].</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

AplicacionUsuarioAC/src/AplicacionUsuarioAC/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"].</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

AplicacionUsuarioAC/src/AplicacionUsuarioAC/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="6000">
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
        <li data-target="#myCarousel" data-slide-to="3"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
        <div class="item active imgContainer">
            <img src="~/images/Background.jpg" alt="ASP.NET" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                   Welcome
                </p>
            </div>
        </div>
        <div class="item imgContainer">
            <img src="~/images/Background.jpg" alt="Visual Studio" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    To
                </p>
            </div>
        </div>
        <div class="item imgContainer">
            <img src="~/images/Background.jpg" alt="Elias" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Elias
                </p>
            </div>
        </div>
        <div class="item imgContainer">
            <img src="~/images/Background.jpg" alt="Page" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    TestPage
                </p>
            </div>
        </div>
    </div>
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

AplicacionUsuarioAC/src/AplicacionUsuarioAC/Views/Listar/AltaUsuario.cshtml
@model AplicacionUsuarioAC.Models.Usuario

<div class="modal-dialog">
    <div class="modal-content">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">×</span><span class="sr-only">Close</span></button>
            <h4 class="modal-title">Nuevo Usuario</h4>
        </div>
        <div class="modal-body">
            <form id="nuevo-usuario">
                <div class="controls span6">
                    <div class="form-group">
                        @Html.LabelFor(u => u.Nombre, new { @class = "control-label" })
                        @Html.TextBox("Nombre", "", new { @class = "form-control", @type = "text", placeHolder = "Introduzca su nombre" })
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(u => u.Email, new { @class = "control-label" })
                        @Html.TextBox("Email", "", new { @class = "form-control", @type = "text", placeHolder = "Introduzca su email" })
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(u => u.Pais, new { @class = "control-label" })
                        @Html.TextBox("Pais", "", new { @class = "form-control", @type = "text", placeHolder = "Introduzca el pais donde vive" })
                    </div>
                </div>
                
                <div class="controls span6">
                    <div class="form-group">
                        @Html.Label("Estado", "Activo/Suspendido", new { @class = "control-label" })
                        @Html.CheckBox("Estado", false, new { @class = "" })
                    </div>
                </div>
            </form>
        </div><!-- /.modal-body-->
        <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            <button id="save" type="button" class="btn btn-primary">Save changes</button>
        </div>
    </div><!-- /.modal-content -->
</div><!-- /.modal-dialog -->

AplicacionUsuarioAC/src/AplicacionUsuarioAC/Views/Listar/Index.cshtml
@{
}

AplicacionUsuarioAC/src/AplicacionUsuarioAC/Views/Listar/Usuarios.cshtml
@model IEnumerable<AplicacionUsuarioAC.Models.Usuario>

@{
    ViewData["Title"] = "Usuarios";  
}
Filtrar: <input id="filtrar" class="filtro" placeholder="introduzca el nombre del usuario..."/>

<table id="tablaUsuarios" class="table">

    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Nombre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Pais)
            </th>
            <th>
                @Html.DisplayName("Ultima conexión")
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Estado)
            </th>
        </tr>
    </thead>

    @foreach (var usuario in Model)
    {
        var tresMeses = usuario.FechaUltimoLogin.CompareTo(DateTime.Now.AddMonths(-3));
        var unMes = DateTime.Now.AddMonths(-1);
        string clase = string.Empty;

        if ( tresMeses >= 0)
        {
            if (usuario.FechaUltimoLogin.CompareTo(unMes) <= 0)
            {
                clase = "amarillo";
            }

        }else
        {
            clase = "rojo";

        }

        <tr id="@usuario.Email" name="@usuario.Nombre" class="@clase">
            <td name="nombre">
                @Html.DisplayFor(modelItem => usuario.Nombre)
            </td>
            <td name="email">
                @Html.DisplayFor(modelItem => usuario.Email)
            </td>
            <td name="pais">
                @Html.DisplayFor(modelItem => usuario.Pais)
            </td>
            <td>
                @Html.DisplayFor(modelItem => usuario.FechaUltimoLogin)
            </td>
            <td name="estado">
                @(usuario.Estado ? "Activo" : "Suspendido")
            </td>
            <td >
                <span  class="eliminar glyphicon glyphicon-remove"/>
            </td>
        </tr>
    }

</table>

<button class="btn btn-default agregar">Agregar usuario</button>

<div class="modal" id="modal"></div>



<environment names="Development">
    <link rel="stylesheet" href="~/css/usuarios.css"/>
    <script src="~/js/usuarios.js" asp-append-version="true"></script>
</environment>

AplicacionUsuarioAC/src/AplicacionUsuarioAC/Views/Listar/_usuario.cshtml
@model AplicacionUsuarioAC.Models.Usuario

<tr id="@Model.Email" name="@Model.Nombre" class= "">
    <td>
        @Html.DisplayFor(modelItem => Model.Nombre)
    </td>
    <td>
        @Html.DisplayFor(modelItem => Model.Email)
    </td>
    <td>
        @Html.DisplayFor(modelItem => Model.Pais)
    </td>
    <td id="fecha">
        @Html.DisplayFor(modelItem => Model.FechaUltimoLogin)
    </td>
    <td>
        @(Model.Estado ? "Activo" : "Suspendido")
    </td>
</tr>

AplicacionUsuarioAC/src/AplicacionUsuarioAC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AplicacionUsuarioAC</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">AplicacionUsuarioAC</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Listar" asp-action="Usuarios">Listar usuarios</a></li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2016 - AplicacionUsuarioAC</p>
        </footer>
    </div>

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("scripts", required: false)
</body>
</html>